/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerkoopRouteImport } from './routes/verkoop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as RequestIdRouteImport } from './routes/request.$id'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminInkoopPrijzenRouteImport } from './routes/_authenticated/admin.inkoop-prijzen'

const VerkoopRoute = VerkoopRouteImport.update({
  id: '/verkoop',
  path: '/verkoop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestIdRoute = RequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminInkoopPrijzenRoute =
  AuthenticatedAdminInkoopPrijzenRouteImport.update({
    id: '/admin/inkoop-prijzen',
    path: '/admin/inkoop-prijzen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/verkoop': typeof VerkoopRoute
  '/account': typeof AuthenticatedAccountRoute
  '/new': typeof AuthenticatedNewRoute
  '/request/$id': typeof RequestIdRoute
  '/u/$id': typeof UIdRoute
  '/admin/inkoop-prijzen': typeof AuthenticatedAdminInkoopPrijzenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/verkoop': typeof VerkoopRoute
  '/account': typeof AuthenticatedAccountRoute
  '/new': typeof AuthenticatedNewRoute
  '/request/$id': typeof RequestIdRoute
  '/u/$id': typeof UIdRoute
  '/admin/inkoop-prijzen': typeof AuthenticatedAdminInkoopPrijzenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/verkoop': typeof VerkoopRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/request/$id': typeof RequestIdRoute
  '/u/$id': typeof UIdRoute
  '/_authenticated/admin/inkoop-prijzen': typeof AuthenticatedAdminInkoopPrijzenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/login'
    | '/verkoop'
    | '/account'
    | '/new'
    | '/request/$id'
    | '/u/$id'
    | '/admin/inkoop-prijzen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/login'
    | '/verkoop'
    | '/account'
    | '/new'
    | '/request/$id'
    | '/u/$id'
    | '/admin/inkoop-prijzen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/feed'
    | '/login'
    | '/verkoop'
    | '/_authenticated/account'
    | '/_authenticated/new'
    | '/request/$id'
    | '/u/$id'
    | '/_authenticated/admin/inkoop-prijzen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  VerkoopRoute: typeof VerkoopRoute
  RequestIdRoute: typeof RequestIdRoute
  UIdRoute: typeof UIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verkoop': {
      id: '/verkoop'
      path: '/verkoop'
      fullPath: '/verkoop'
      preLoaderRoute: typeof VerkoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$id': {
      id: '/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof RequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/inkoop-prijzen': {
      id: '/_authenticated/admin/inkoop-prijzen'
      path: '/admin/inkoop-prijzen'
      fullPath: '/admin/inkoop-prijzen'
      preLoaderRoute: typeof AuthenticatedAdminInkoopPrijzenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedAdminInkoopPrijzenRoute: typeof AuthenticatedAdminInkoopPrijzenRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedAdminInkoopPrijzenRoute: AuthenticatedAdminInkoopPrijzenRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  VerkoopRoute: VerkoopRoute,
  RequestIdRoute: RequestIdRoute,
  UIdRoute: UIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
